# Generated by Django 5.0.6 on 2024-05-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vacancies_alter_faq_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacancies',
            new_name='Contacts',
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
    ]
