# Generated by Django 5.0.6 on 2024-05-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_vacancies_contacts_alter_contacts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='image',
            field=models.ImageField(blank=True, height_field=100, upload_to='images', width_field=100),
        ),
    ]
