# Generated by Django 5.0.6 on 2024-05-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_vacancion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancion',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
