# Generated by Django 5.0.6 on 2024-05-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(verbose_name='Логин')),
                ('password', models.TextField(verbose_name='Пароль')),
                ('fullName', models.TextField(verbose_name='ФИО')),
                ('phone', models.TextField(verbose_name='ФИО')),
                ('pasport', models.TextField(verbose_name='Паспорт')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
