# Generated by Django 5.0.6 on 2024-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cost',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='job',
            name='text',
            field=models.TextField(verbose_name='Услуга'),
        ),
    ]
