# Generated by Django 5.0.6 on 2024-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_job_cost_alter_job_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cost',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
