# Generated by Django 5.0.6 on 2024-05-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_job_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='make',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
