# Generated by Django 5.0.6 on 2024-05-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_job_make'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestId', models.IntegerField(verbose_name='Id заказа')),
                ('JobId', models.IntegerField(verbose_name='Id услуги')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Request',
            },
        ),
        migrations.CreateModel(
            name='RequestId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField(verbose_name='Id пользователя')),
                ('ready', models.BooleanField(default=False, verbose_name='Заказ выполнено')),
            ],
            options={
                'verbose_name': 'RequestId',
                'verbose_name_plural': 'RequestId',
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='make',
        ),
    ]
