# Generated by Django 5.0.6 on 2024-05-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_requestid_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestid',
            name='cost',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
    ]
