# Generated by Django 5.0.6 on 2024-05-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_requestid_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.IntegerField(verbose_name='ФИО пользователя')),
                ('text', models.IntegerField(verbose_name='Текст комментария')),
                ('data', models.DateTimeField(verbose_name='Время комментария')),
                ('mark', models.IntegerField(verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AlterField(
            model_name='requestid',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='Заказ выполнен'),
        ),
    ]
