# Generated by Django 5.0.6 on 2024-05-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_comment_alter_requestid_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='UserName',
            field=models.TextField(verbose_name='ФИО пользователя'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
    ]
