# Generated by Django 5.0.6 on 2024-05-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='img',
            field=models.ImageField(height_field=100, null=True, upload_to='article', width_field=100),
        ),
    ]
