# Generated by Django 5.0.6 on 2024-05-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_contacts_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='img',
            field=models.ImageField(null=True, upload_to='article'),
        ),
    ]
